-- Generated by nwg-displays on 2026-08-23 at 23:11:34. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1
})
